
name: Run / Test / Build (manual)

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Pasirink, ką vykdyti"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - test
          - lint
          - run-script
          - build-docker
      name:
        description: "Argumentas skriptui (--name)"
        required: false
        default: "Kuponex"

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        if: ${{ inputs.task == 'lint' || inputs.task == 'all' }}
        run: flake8 .

      - name: Tests (pytest)
        if: ${{ inputs.task == 'test' || inputs.task == 'all' }}
        run: pytest -q

      - name: Run Python script
        if: ${{ inputs.task == 'run-script' || inputs.task == 'all' }}
        run: python src/main.py --name "${{ inputs.name }}"

      - name: Build Docker image
        if: ${{ inputs.task == 'build-docker' || inputs.task == 'all' }}
        run: docker build -t kuponex-app:ci .

      - name: Run Docker container (smoke test)
        if: ${{ inputs.task == 'build-docker' || inputs.task == 'all' }}
        run: docker run --rm kuponex-app:ci --name "${{ inputs.name }}"
